name = "backend"
compatibility_date = "2024-02-08"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTQ3NDNkYzMtNThlNi00OWMzLWEyNGQtOTczN2VjMTVhMTBmIiwidGVuYW50X2lkIjoiZjUwNGI4YTBjMDc3ZmI3MDE3OWUwMGMwNWM0YWUxZjk5MTU1ZmJjOTBiMmVkNWFkODUzODMyZGU5YTZlOGIzYiIsImludGVybmFsX3NlY3JldCI6ImQ1YjlkNDk1LWYxZTgtNDA0OS1iZWRlLTJmMTY1MDQ0MTc1MyJ9.WWAXQCaQS3RdEQpSm9Q-L0rjqCM5EcKrtLicinoSCG4"
JWT_SECRET = "harsh-secret"